### ISSUE TITLE
子供の入力を可能にする

### ISSUE THREAD

**Issue by smellman** [project-inclusive/OpenFisca-Shibuya#1]
子供の編集が出来ないため、必ず補助金がなしで返ってきてしまう。

子供の入力が出来るようにする。

**Comment by SnoozingJellyfish** [comment]
# [WIP] furuhashi/input_children_info ブランチで作業中

## Done
- 「あなた」の属性に「子どもの数」を追加し、その数分子ども情報の入力フォームが生成されるようにした。
- 子どもの年齢がOpenFiscaの計算に反映されるようにした。

## TODO
- 子どもの障害者手帳情報がOpenFiscaの計算に反映されるようにする。
- 「あなた」の属性に「子どもの数」が変化したときに子どもの情報がリセットされるようにする。

**Comment by SnoozingJellyfish** [comment]
## [完了] furuhashi/input_children_info ブランチからプルリクエスト
- [x] 子どもの障害者手帳情報がOpenFiscaの計算に反映されるようにする。
- [x] 「あなた」の属性に「子どもの数」が変化したときに子どもの情報がリセットされるようにする。
- [x] 属性や現在日時など汎用的に扱えるようにファイルや関数を整理

**Comment by SnoozingJellyfish** [comment]
@smellman 
ご確認ありがとうございました。マージされたのでissueをクローズします。
