### ISSUE TITLE
特別児童扶養手当のテスト

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Shibuya#17]
- [ ] [渋谷区公式HP](https://www.city.shibuya.tokyo.jp/kodomo/teate/teate/jido_f.html)の情報を元に、特別児童扶養手当の条件をテストするパターンをCSV形式で作成する。
- [ ] テスト自動作成プログラムを用いて、テストパターンのCSVファイルをyamlのテストファイルに変換する。
- [ ] yamlのテストファイルによるテストが全て成功することを確認する。成功しない場合、openfisca_japan/variables/福祉/育児/特別児童扶養手当.pyを修正し、再テストする。

**Comment by hiranoowo** [comment]
下記は東京都の資料ですが、2.特別児童扶養手当を受給することができる方 が参考になるのではないかと思います。
https://www.fukushihoken.metro.tokyo.lg.jp/shinsho/teate/toku_ji.html

**Comment by SnoozingJellyfish** [comment]
東京都や他の自治体の資料を確認したところ、障害者手帳の等級だけから特別児童扶養手当の等級は決められないようです。例えば、身体障害者手帳1級に該当する障害のうち、特別児童扶養手当の1級・2級に認められるものがそれぞれあります。（参考：[厚労省の身体障害者手帳HP](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/shougaishahukushi/shougaishatechou/index.html)）
ユーザーが障害内容について細かく入力するのは煩雑であり、OpenFiscaの趣旨からもそこまで考慮する必要はなさそうです。
特別児童扶養手当の1級・2級は支給額が異なるため、OpenFiscaでは最大額（1級）と最小額（2級）を算出し、その幅を持たせてユーザーに表示するのが良いかと思います。
そうすると、テスト作成時も最小額と最大額をそれぞれ記載する必要があります。
金額の幅がない手当については、最小額か最大額のどちらかのみ記載すれば良いと思います。

**Comment by SnoozingJellyfish** [comment]
pull request #36 によってテスト完了のためクローズ
