### ISSUE TITLE
年収から所得を算出する

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Shibuya#18]
各種手当には所得額の情報が必要ですが、ユーザーは所得より年収の方を把握していることが多いと思われます。  
そのため、年収から所得を算出できることが望ましいです。  
各種手当の所得制限に用いられるのは「給与所得」です。  
これは、自営業の場合は年収から必要経費を差し引いたもの、  
会社などから給与される場合は年収から「給与所得控除」を差し引いたものになります。
OpenFisca Shibuyaでは、ひとまず年収から一意に算出される「給与所得控除」を用いて所得を計算しようと思います。  
給与所得控除の算出方法は[国税庁HP「給与所得控除」](https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1410.htm)を参照ください。
以下TODOです。  
- [ ] `openfisca_japan/variables/所得.py`に給与所得控除を収入から算出するclassを作成する。
- [ ] `openfisca_japan/variables/所得.py`の「所得」classを収入から給与所得控除を差し引いて算出するように修正する。
- [ ] `openfisca_japan/tests`フォルダ以下に給与所得控除と所得の境界値テストを行うテストファイルを作成・実行し、クリアすることを確認する。テスト方法はREADMEの「開発方法」を参照してください。

これらが達成できたら、別issueにて以下の実装を行う必要があります。
- dashboard（フロントエンド）に、給与所得控除を元に所得を算出している（自営業者の場合は実際の所得額と異なる）ことを注記する。
- テスト自動生成スクリプトで所得から年収を逆計算するように修正する。（CSVのテストパターンを作成する際、各種手当の条件に記載されている所得額を年収に換算するのが煩雑なので、CSVには所得を記載しテスト自動生成スクリプトで年収に換算する方が望ましいため。）

**Comment by Syuparn** [comment]
こちらのissue着手したいと思います。

**Comment by SnoozingJellyfish** [comment]
@Syuparn さん、ありがとうございます！
[このリポジトリのWikiの「OpenFiscaフレームワークのTips」](https://github.com/project-inclusive/OpenFisca-Shibuya/wiki/OpenFisca%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AETips) にOpenFisca特有の挙動や開発メモをまとめているので、もし詰まるところがあれば参照するとヒントが見つかるかもしれません。  
もちろんこのissueのコメントで質問していただいても構いません。  
新たに発見されたOpenFiscaのTipsがありましたら、私の方でWikiに追記するので教えていただけると幸いです。

**Comment by Syuparn** [comment]
@SnoozingJellyfish 
ありがとうございます、参考にさせていただきます！

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
プルリクありがとうございました！内容確認できたのでマージしました。  
本issueはクローズします。  
それに伴い、以下の内容を別issueに追記します。
- dashboard（フロントエンド）に、給与所得控除を元に所得を算出している（自営業者の場合は実際の所得額と異なる）ことを注記する。  
→ #9 に追記します。

- テスト自動生成スクリプトで所得から年収を逆計算するように修正する。（CSVのテストパターンを作成する際、各種手当の条件に記載されている所得額を年収に換算するのが煩雑なので、CSVには所得を記載しテスト自動生成スクリプトで年収に換算する方が望ましいため。）  
→yamlのテストファイル上での入力情報は、本来は途中で算出される値を手入力してもエラーにならない。  
そのため、従来通りCSVのテストパターンの所得はそのままyamlのテストファイルに入力情報として記載する。（テスト自動生成スクリプトは修正しない。）

**Comment by Syuparn** [comment]
@SnoozingJellyfish 
レビューありがとうございます！今後の進め方承知しました。
