### ISSUE TITLE
ホスティング先を探す

### ISSUE THREAD

**Issue by matobaa** [project-inclusive/OpenFisca-Shibuya#2]
フロントをどこに置くか
バックエンド(Python)をどこで動かすか
が決まったらクローズ

**Comment by matobaa** [comment]
参考: [Herokuの代替サービス30選](https://qiita.com/rana_kualu/items/f7fc4916b7dc9797839e)

**Comment by SnoozingJellyfish** [comment]
@Koichiro-Shiratori 　　　
バックエンドのOpenFisca APIサーバーは、ひとまずGoogle CloudのCloud runというサービスを使ってみます。　　
このサービスを使って、Githubリポジトリにプッシュが行われたタイミングで、公開されているバックエンドサーバーも自動で更新されるようにしたいと思っています。そのために、githubリポジトリに「Google Cloud Build」のアプリケーションをインストールする必要があります。ただ私はインストールする権限がないので、Ownerにインストールリクエストを出しました。お手数ですが、**proj-inclusiveのグループページかOpenFisca-Shibuyaのリポジトリページに何らかの通知が来ていると思うので、承認していただけないでしょうか？**　　

ちなみにGoogle CloudのCloud Runを試す理由は以下の3つです。
- 無料枠があり、それを超えても料金は安い(はず)
- dockerイメージがあれば簡単にデプロイできる。クラウドの設定もさほどややこしくなさそう。
- 他のサービスとの連携が可能。可用性、セキュリティも信頼度が高い。

**Comment by SnoozingJellyfish** [comment]
Cloud Runは当面は無料枠に収まると思うので、Google Cloudのアカウントは一旦私のものを使います。

**Comment by Koichiro-Shiratori** [comment]
@SnoozingJellyfish 
反応遅れてすみません、承認したと思います！！

**Comment by SnoozingJellyfish** [comment]
フロントエンドをGithub Pages、バックエンドをGoogle CloudのCloud Runでビルド・デプロイするようにしました。  
mainブランチにプッシュされると、自動でフロントエンド・バックエンドともにビルド・デプロイが行われます。  
作成されたホームページは https://project-inclusive.github.io/OpenFisca-Shibuya/ に公開されています。
試験的な運用のため今後ホスティング先を変える可能性はありますが、当面は問題ないと思われるため、本issueはクローズします。
