### ISSUE TITLE
児童手当の必要十分なテストを作成し、それらが全て成功するようにする

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Shibuya#5]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

バックエンドのdocker環境を起動しました。（README.mdの「バックエンドのみ環境構築・起動」参照）  
自動作成した児童手当のテストファイルをテストしました。（README.mdの「テスト条件・結果を記載したCSVファイルからyamlのテストファイルを作成する方法」参照） 

### Here is what I expected to happen:

全てのテストに成功する。

### Here is what actually happened:

テストID=31 で失敗する。

### Here is data (or links to it) that can help you reproduce this issue:

毎回必ず再現する。

## 原因及び現在の問題

児童手当の詳細については[公式HP](https://www.city.shibuya.tokyo.jp/kodomo/teate/teate/jido_t.html)を参照してください。

### テスト条件・結果を記載したCSVファイル（以下、表と記載）の問題

1. 表の生年月日と満年齢が合致しないようです。2021/12生まれは2023/4時点では満1歳となります。境界値テストを兼ねると生年月日を直すのが良いと思われます。
1. 中学生かどうかを年齢(15歳以下)で判定しているため、表上、中学生以上とするには「16歳」を設定する必要があります。
1. 児童手当の計算対象となる第n子の設定方法に誤りがあります。第1子から第3子の数え方については、18歳になってから最初の3月31日までのお子さんを、出生順で数えます。  
つまり、第1子 太郎：22歳、第2子 二郎：16歳、第3子 三郎：10歳の時、児童手当の計算をする際は**二郎が第1子**、**三郎が第2子**となります。

### OpenFiscaの計算ロジックの問題

1. 第3子のロジックが variables 定義にないため、テストID=31 でテストが失敗します。
2. 所得**上限**限度額は考慮されているが、所得**制限**限度額は考慮されていません。所得制限限度額以上、所得上限限度額未満の所得の場合、特例給付となります。

**Comment by SnoozingJellyfish** [comment]
学年の算出方法が誤っていたので修正し、mainブランチにプルリクエスト・マージしました。
これにより早生まれと遅生まれで異なる学年が算出されます。
児童手当は小学生・中学生の区分で計算方法が変わるため、**年齢**ではなく**学年**で境界値テストを作成するようお願いします。
その際、学年は小学n年生はn, 中学m年生はm+6, 高校l年生はl+9 を設定してください。（例えば、小学2年生は2, 中学2年生は8, 高校2年生は11となります。）

**Comment by minosys-jp** [comment]
@SnoozingJellyfish 
調整ありがとうございます。
**学年** を記載してもらった方が間違いが少ないように思います。
この場合、早生まれ遅生まれが区別できなくなりますが、自動的に両方のテストケースを生成するのが良いですかね。
条件が3つあるとテストケースが8倍に増えてしまいますが。

**Comment by SnoozingJellyfish** [comment]
@minosys-jp 
コメントありがとうございます！説明不足でしたので補足します。  
児童手当では、「3歳以上から小学校修了前まで」というような学年と年齢が混在した条件もあるため、年齢と学年をそれぞれ指定できた方が良いかもしれません。この場合だと、「3歳未満」、「3歳以上」、「小学校修了前」、「小学校修了後」の区別の仕方になるでしょうか。
早生まれと遅生まれは「openfisca_japan/tests/年齢と学年/学年.yaml」のテストで、それぞれ正しく学年を計算できるか確認しています。そのため、各種手当のテストでは早生まれと遅生まれの区別はしていただかなくて構いません。

**Comment by Koichiro-Shiratori** [comment]
@minosys-jp @SnoozingJellyfish 
諸々ありがとうございます！　確認させてください。

1. 今後、条件からCSVファイルが自動生成できる可能性もあるが、当面はテスト作成元CSVファイルを作り進める
2. テスト作成元CSVファイルの条件設定は、現在の「生年月日」から「年齢」と「学年」に変更する

こちらで他の制度の分もCSVファイルを少しずつ作成していこうと思いますが、他に注意すべき事項があれば教えてください。よろしくお願いします！

**Comment by SnoozingJellyfish** [comment]
@Koichiro-Shiratori 
1. 当面はCSVファイル作成を進めていただけると助かります。だんだん慣れてきたら、頭の中でどのようなルールに従って各種手当の条件からCSVファイルに変換しているか、少しずつ明文化してみるのが次の一歩になるかと思います。
そのルールのうち、各種手当で共通するロジックがあればプログラムで自動化できます。

2. 生年月日から学年・年齢への変更をお願いします！

**Comment by SnoozingJellyfish** [comment]
@minosys-jp , @Koichiro-Shiratori 
児童手当を含んだ児童関連の各種手当の計算方法を修正し、mainブランチにマージしました。  
正しく計算できているかはアドホック的にテストしましたが、網羅的なテストは作成いただいている(自動)テストによって実施したいと思います。  
フロントエンドも修正したので、ブラウザ入力からも結果を確認できます。

**Comment by Koichiro-Shiratori** [comment]
@SnoozingJellyfish 
ありがとうございます！！

**Comment by SnoozingJellyfish** [comment]
ユーザーの入力情報から支給額を一意に決められない手当は、OpenFiscaでは最大額と最小額を算出するようにしました。
そのため、テスト作成時も最小額と最大額をそれぞれ記載する必要があります。
金額の幅がない手当については、最小額か最大額のどちらかのみ記載すれば良いと思います。

**Comment by SnoozingJellyfish** [comment]
pull request #36 によってテスト完了のためクローズ
