### ISSUE TITLE
各種手当とその合計の計算結果を見やすく表示する。

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Shibuya#9]
現在、各種手当の計算結果はjson形式でフォームの下に表示されます。  
それを手当額が0でない手当の種類と額が見やすく表示されるようにしたいです。  
各種手当の合計も表示できるとわかりやすいです。

**Comment by SnoozingJellyfish** [comment]
各種手当の渋谷区HPの参照リンクも表示して、詳しくは自治体に問い合わせてもらう旨も記載した方が良さそうです。

**Comment by JQinglong** [comment]
鉄は熱いうちに打てと思いつつ、時間がとれませんが、本Issueに手を付けようと思いました。
OpenFisca-Shibuya/dashboard/src/components/form.tsx
で、現状の
`{result && <pre>{JSON.stringify(result.世帯.世帯1, null, 2)}</pre>}`
の部分で、下記のように記載すれば表になると思います。
`      <ul class="list-group mb-3">
        {result && Object.entries(result.世帯.世帯1).map((val, index) =>
          <li key={index} class="list-group-item d-flex justify-content-between lh-sm">

            <div>
            <h6 class="my-0">{val[0]}</h6>
            <small class="text-muted">{Object.keys(val[1])[0]}</small>
          </div>
          <span class="text-muted">{Number(Object.values(val[1])[0]).toLocaleString()} 円</span>

          </li>
        )}
      </ul>`
上記HPの参照リンクを表示する件は対応できていませんが、日付の代わりに表示する等でもよいかと思いました。
ただ、それをどう引っ張ればよいかは分かりませんでした。
そういった相談はここでしてよいでしょうか？Slackのほうがよさそうでしょうか？

**Comment by SnoozingJellyfish** [comment]
@JQinglong 
ありがとうございます！issueに関する質問はこちらでしていただいて構いません。OpenFisca全般についてはslackで相談していただいても問題ありません。

渋谷区公式HPの参照リンクですが、ひとまずaタグを使って以下のように記載するだけでも良いかなと思っていました。  
`<a href="https://www.city.shibuya.tokyo.jp/kodomo/teate/teate/jido_t.html">渋谷区の児童手当HP</a>`  
手当によって渋谷区HPの参照リンク先が変わるのですが、`openfisca_japan/variables/福祉/育児`フォルダ以下の各種手当のpythonファイル内に参照リンクを記載しています。  
日付の代わりに表示するというのは良さそうですね！

ちなみにご存知かもしれませんが、実際に実装する際は、Reactだと`class`が予約語で使えないので`className`に変更する必要があります。それと、`result.世帯.世帯1`の型定義をしっかりしてないので、val[1]がコンパイルエラーになる状態です。フロントエンドに詳しくないので、適切な直し方がわかっていないのですが…

**Comment by SnoozingJellyfish** [comment]
フォームから入力された収入に対し、OpenFisca内部で給与所得控除分を引いて所得を算出する処理を加えました。  
ただし、自営業者の所得は給与所得控除によって計算されません。  
そのため、給与所得控除を元に所得を算出している（自営業者の場合は実際の所得額と異なる）ことをページ上に注記する必要があります。

**Comment by SnoozingJellyfish** [comment]
備忘のためのメモです。

- 障害者を対象とした手当の給付条件には、障害者手帳を持っていなくても同等の障害があれば対象となると記載されています。
そのため、HPにもその注記が必要です。
（参考：[渋谷区の障害者を対象とした手当](https://www.city.shibuya.tokyo.jp/kurashi/shogaisha/teate.html)）

- 入力情報から一意に支給額を決められないテストがあり、OpenFiscaのバックエンドでは`(手当名)_最大`あるいは`(手当名)_最小`のキーによって、最小額と最大額を返すようにしています。そのため、GUIでは「(最小額)~(最大額)」のように表示するのが良さそうです。

**Comment by JQinglong** [comment]
@SnoozingJellyfish 
コメントありがとうございます。
確かに計算のたびに取得する必要はないですね、最初に読み込む方法をやってみたいと思います。
最近の修正、バックエンドURLについては承知しました。

**Comment by JQinglong** [comment]
@SnoozingJellyfish 
最初ということで、まだプルリク出してませんが、このように直してみました。
何か気になる点がないかみていただけるとありがたいです。
https://github.com/JQinglong/OpenFisca-Shibuya/commit/cef08d286f273f399b1b59197ada60128621e00c

**Comment by SnoozingJellyfish** [comment]
@JQinglong 
ありがとうございます！手元で実行してみましたが、とても見やすくなっていると思います。勉強になります。  
2点コメントです。
- 参照先がどこかわかるよう、リンクの文言に「（渋谷区HP）」の記載を追加していただきたいです。
- リンクの下の日付は現在の日付なので不要かなと思います。Objectキーの日付はOpenFiscaの仕様のために入れています。

**Comment by JQinglong** [comment]
@SnoozingJellyfish 
コメントありがとうございます。では、この方向で、ご指摘の対応もしていこうと思います。
確認しやすいように、ブランチ切ってそちらにプルリク出した方が良いですよね。

**Comment by SnoozingJellyfish** [comment]
@JQinglong 
はい、ブランチ切って、OpenFisca-Shibuya/mainブランチにプルリクお願いします！

**Comment by SnoozingJellyfish** [comment]
Pull request #34 で手当の合計額、最大額、最小額を表示するように修正し、残件に対応したためクローズします。
